# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限名')),
                ('url', models.CharField(max_length=64, verbose_name='含正则url')),
                ('is_menu', models.BooleanField(verbose_name='是否为菜单')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=32, verbose_name='角色名')),
                ('role2per', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='所具有的权限')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('user2role', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='所属角色')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
